### PR TITLE
feat: add preview icon when clicking outside the document

### LINKED ISSUE #615: Preview icon disappears when clicking outside the document
This issue came from [Typst Preview#262](https://github.com/Enter-tainer/typst-preview/issues/262)

**Describe the bug**
When I click outside the typst document (but keeping it open), the preview icon in the top right-hand corner disappears.

https://github.com/Enter-tainer/typst-preview/assets/54775010/a8a30463-3d27-4fc6-b3a7-c253a08b2947

**To Reproduce**
+ Open a typst document
+ Click outside the document (in the terminal or in the directory tree)

**Expected behavior**
The preview icon should remain visible as long as the document is open, even if the user clicks outside the document.

**Package/Software version:**

```plain
tinymist
Build Timestamp:     2024-08-26T16:22:10.986712173Z
Build Git Describe:  v0.11.20
Commit SHA:          1f9a42c2e863f6b1fe8624da796e47adf44a9a83
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.11.1
```

### PR DESCRIPTION
**Pull request by supersurviveur**
Here is another try to fix #615.

I store the current activeEditor to retreive it even if the user is in the output pannel. I change the activeEditor when another typst document is opened.
This way the preview button always works, even in the output pannel.

### CODE REVIEW

**Comment by Myriad-Dreamin** [comment]
Hi~ Thank you for go on fixing this issue. The current solution still has some problems:
- Both `vscode.TextEditor` and `vscode.TextDcoument` can be disposed at any time, so we cannot access or hold them across callbacks. It also prevents GC of these objects.
- If all typst documents are not visible in window, we should hide the preview icon, to save precious space in the top bar. To control visibility programatically, we can use [contextKey](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context).

  Example usage:

  https://github.com/Myriad-Dreamin/tinymist/blob/2c38695b6f922d9978d2de53c36c534a17cf0a58/editors/vscode/src/extension.ts#L65-L67

  https://github.com/Myriad-Dreamin/tinymist/blob/2c38695b6f922d9978d2de53c36c534a17cf0a58/editors/vscode/package.json#L47

**Comment by supersurviveur** [comment]
The second issue seems to be easy to solve with a context. But I think that it's not even needed, because the preview icon is shown only if a typst document is opened and is visible.

The first one is harder to solve, maybe we can check is the `textEditor` is disposed when the preview is launched, and use the `window.activeEditor` by default.

**Comment by supersurviveur** [comment]
Now the activeEditor is dropped when it is closed. Moreover, `window.activeEditor` is used if the editor stored is `undefined`. This way the second issue is not a problem and it's less a problem for the GC.

However, now when I click on the document, it shows me the source in another textEditor...

**Comment by Myriad-Dreamin** [comment]
> However, now when I click on the document, it shows me the source in another textEditor...
> EDIT: I also have the issue without my modifications.

https://github.com/Myriad-Dreamin/tinymist/issues/534

**Pull request merged**
