### PR TITLE
feat: comment complete for tidy style doc comment

### PR DESCRIPTION
**Pull request by Eric-Song-Nop**
for #1015

### CODE REVIEW

**Comment by Eric-Song-Nop** [comment]
For now this pull request just complete a doc string as comment complete, it is not considering the known type of the parameters, while from my perspective works better when this feature is implemented as a docstring updater or a code action.

**Comment by Myriad-Dreamin** [comment]
I start to experience it and have found several points. We might start to complete a "Document function" only if the comment is a "doc comment" and only contains nothing.
- if user only enters two slashes, they might not purpose to make a documentation.
- we seems to be triggering the completion in the comment everywhere, e.g. when I put a dot in the comment.
   image
- we can also generates documentation for variables.

**Comment by Eric-Song-Nop** [comment]
> if user only enters two slashes, they might not purpose to make a documentation.
> we seems to be triggering the completion in the comment everywhere, e.g. when I put a dot in the comment.

I have stricted the condition. Tbh, why doc comment does not utilize block comment but line comment, it's really annoying.

> we can also generates documentation for variables.
If I know correctly, doc a variable has no specific format right? Do we really need to complete anything for it?

**Comment by Myriad-Dreamin** [comment]
> Tbh, why doc comment does not utilize block comment but line comment, it's really annoying.

Caused that we borrow the format from rust.

> If I know correctly, doc a variable has no specific format right? Do we really need to complete anything for it?

You might know it wrongly. You can document any let binding items.

```typ
/// A swap operation. 
///
/// - a (B): It was b.
/// - b (A): It was a.
/// -> (B, A)
#let (a, b) = (b, a);


/// A simpler example. 
///
/// -> content
#let embedded-file = context metadata(query(<output>));
```

**Review by Myriad-Dreamin — APPROVED** [review]

**Comment by Eric-Song-Nop** [comment]
> You might know it wrongly. You can document any let binding items.
Oh I didn't know this

**Pull request merged**
