### PR TITLE
fix: improve release profile & fix typos

### PR DESCRIPTION
**Pull request by QuarticCat**
- Some building options are too slow for daily dev. I only enable them in the release CI.
- My [typos](https://github.com/crate-ci/typos) plugin keeps complaining so I fixed some.

### CODE REVIEW

**Comment by Myriad-Dreamin** [comment]
surprised that I wrote that many typos but I'm not aware of them for weeks 😹.

I'll run the release steps before merge to avoid breaking release pipeline.

**Comment by Myriad-Dreamin** [comment]
The analyzer's snapshot testing fails. Could you check and update according to https://github.com/Myriad-Dreamin/tinymist/pull/178/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R29?

**Comment by QuarticCat** [comment]
this should fix the CI

**Comment by Myriad-Dreamin** [comment]
Thanks!

**Pull request merged**
