### PR TITLE
feat: fold continue line comments

### PR DESCRIPTION
**Pull request by Eric-Song-Nop**
resolve: #1044

Should be ready

### CODE REVIEW

**Comment by Myriad-Dreamin** [comment]
I assigned the kind of these folding range to `Fol`, to allow us folding/unfolding all comments by one shortcut.

**Review by Myriad-Dreamin — DISMISSED** [review]

**Comment by Myriad-Dreamin** [comment]
We start to maintain some magic mutable state when calculating folding range. This is a signal that the code starts to become unmaintainable. 

```rs
let mut last_line_comment_end_range: Option<FoldingRange> = None;
```

This won't block us to merge this PR because there is an only state related to the conversion loop, but we may need some refactor to identify them uniformally in `LexicalHierarchyWorker`, where we can hold some analysis state in the `Worker` legally.

hint: Conventionally, every struct ends with `Worker` is an independent analyzer.

**Comment by Eric-Song-Nop** [comment]
I am also thinking of getting rid of it, how I really cannot fully understand how the `lexicalhierechy` works clearly, thus I am doing all works in folding_range.

**Comment by Myriad-Dreamin** [comment]
I have tried to refactor it a bit: https://github.com/Eric-Song-Nop/tinymist/compare/fold_line_comments...Myriad-Dreamin:fold_line_comments

I mainly just avoid pushing `Space`s to the stack and reuse some stuff from the existing comment matcher.

**Comment by Eric-Song-Nop** [comment]
I've tested and it looks good to me.

**Review by Myriad-Dreamin — APPROVED** [review]

**Comment by Eric-Song-Nop** [comment]
Might need to be merged quickly before other codes changed way too much.

**Pull request merged**
