### PR TITLE
fix: import item complete

### PR DESCRIPTION
**Pull request by Eric-Song-Nop**
fix: `import "lib.typ": |` cannot complete

problem from #952

### CODE REVIEW

**Comment by Myriad-Dreamin** [comment]
Still cannot complete directly after the colon:

```typ
#import "../src/basic/mod.typ":| 
```

image

**Comment by Eric-Song-Nop** [comment]
seems there has to be a space after the colon

**Comment by Myriad-Dreamin** [comment]
I fixed it by adding another matcher on colon marker, but I then find it does not work after comma as well.

```typ
#import "../src/basic/mod.typ": code,| 
```

**Comment by Myriad-Dreamin** [comment]
it is probably nice enough. The only missing thing is to add more testing about the colon and comma completion.

**Comment by Eric-Song-Nop** [comment]
> it is probably nice enough. The only missing thing is to add more testing about the colon and comma completion.

I made some

**Review by Myriad-Dreamin — APPROVED** [review]

**Pull request merged**
